### ISSUE TITLE
Node died 

### ISSUE THREAD

**Issue by yasiryagi** [rizon-world/testnet#6]
goroutine 63021 [running]:
github.com/tendermint/tendermint/libs/autofile.(*Group).readGroupInfo(0xc00b0cd760, 0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.9/libs/autofile/group.go:365 +0x52b
github.com/tendermint/tendermint/libs/autofile.(*Group).checkTotalSizeLimit(0xc00b0cd760)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.9/libs/autofile/group.go:274 +0x69
github.com/tendermint/tendermint/libs/autofile.(*Group).processTicks(0xc00b0cd760)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.9/libs/autofile/group.go:245 +0x85
created by github.com/tendermint/tendermint/libs/autofile.(*Group).OnStart
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.9/libs/autofile/group.go:140 +0x68

**Comment by yasiryagi** [comment]
seems related to https://hub.cosmos.network/main/validators/validator-setup.html 

#Problem #2: My gaiad crashes because of too many open files

**Comment by YogaSakti** [comment]
the problem you are facing is `too many open files` 

here's the [solution ](https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/)
